import * as THREE from 'three';
import {createGame,active,switchHero,attack,heal,dodge,tick,HEROES} from './combat.js';
import './style.css';
document.querySelector('#app').innerHTML=`<canvas id="view" aria-label="3D fantasy combat arena"></canvas><header><small>CHAPTER 1 · THE EMBER RUINS</small><h1>Defeat the Ember Guardian</h1><div><button id="pause">Pause</button><button id="restart">Restart</button></div></header><section id="boss"><label>EMBER GUARDIAN <span id="boss-state"></span></label><progress id="boss-hp" max="650" value="650"></progress></section><canvas id="map" width="170" height="170" aria-label="Arena minimap"></canvas><section id="commands"><small>COMMANDS</small><button id="attack">Attack <kbd>J</kbd></button><button id="ability">Ember ability <kbd>K</kbd></button><button id="heal">Healing potion <kbd>H</kbd></button><button id="dodge">Dodge <kbd>Space</kbd></button><p>WASD / arrows move · L block<br>1 / 2 / 3 change character</p></section><section id="party"></section><aside id="message" aria-live="polite"></aside><div id="overlay"><article><small>THREE.JS ACTION RPG</small><h2>Ruins of Ember</h2><p>Lead three heroes through a guardian encounter.<br>Watch the red telegraph, dodge the slam, and strike during recovery.</p><button id="start">Enter the ruins</button><p>Original stylized characters and procedural scenery.</p></article></div><nav id="movement"><button data-key="ArrowLeft">◀</button><button data-key="ArrowUp">▲</button><button data-key="ArrowDown">▼</button><button data-key="ArrowRight">▶</button><button data-key="l">BLOCK</button></nav><div id="error" role="alert"></div>`;
const $=id=>document.getElementById(id),scene=new THREE.Scene();scene.background=new THREE.Color(0x8fc4db);scene.fog=new THREE.Fog(0x8fc4db,35,145);
let renderer;try{renderer=new THREE.WebGLRenderer({canvas:$('view'),antialias:true});}catch(e){$('error').textContent='WebGL unavailable. Enable hardware acceleration and reload.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;
const camera=new THREE.PerspectiveCamera(58,1,.1,300);scene.add(new THREE.HemisphereLight(0xd8f0ff,0x465236,2.4));const sun=new THREE.DirectionalLight(0xffe1a9,3);sun.position.set(-30,70,20);scene.add(sun);
function mat(color,metalness=0,roughness=.8){return new THREE.MeshStandardMaterial({color,metalness,roughness});}
const grass=mat(0x607f44),stone=mat(0x87927e),dark=mat(0x152537,.3),gold=mat(0xe6ab48,.7),water=mat(0x51b9cc,.3,.3),wood=mat(0x634c3b),skin=mat(0xe6bd96),glow=new THREE.MeshBasicMaterial({color:0xff802b});
function mesh(geo,material,x,y,z,parent=scene){const m=new THREE.Mesh(geo,material);m.position.set(x,y,z);parent.add(m);return m;}
function box(w,h,d,m,x,y,z,parent=scene){return mesh(new THREE.BoxGeometry(w,h,d),m,x,y,z,parent);}
function cylinder(r,h,m,x,y,z,parent=scene){return mesh(new THREE.CylinderGeometry(r,r,h,10),m,x,y,z,parent);}
box(42,2,42,grass,0,-1,0);box(42,.2,42,stone,0,-2.1,0);box(200,1,200,water,0,-12,0);
for(let i=0;i<32;i++){const a=i/32*Math.PI*2,r=23+(i%3)*2;mesh(new THREE.DodecahedronGeometry(3+i%3,0),stone,Math.cos(a)*r,-1,Math.sin(a)*r);}
for(const x of [-15,15])for(const z of [-13,3,15]){cylinder(.75,5+(z===-13?2:0),stone,x,2.5,z);cylinder(1.1,.35,stone,x,5.2,z);box(2.4,.3,2.4,stone,x,.1,z);}
for(const x of [-15,15]){box(.9,1.5,24,stone,x,.75,0);for(let z=-12;z<=12;z+=4)box(.9,2,1.5,stone,x,2,z);}
box(21,1.8,1,stone,0,.9,-17);for(let x=-9;x<11;x+=4){cylinder(.8,6,stone,x,3,-17);mesh(new THREE.ConeGeometry(1.4,2,8),gold,x,7,-17);}
// Distant fortress and waterfalls, built from original primitives.
for(let i=0;i<9;i++){const x=(i-4)*6,z=-42-(i%3)*5,h=9+(i%4)*4;box(5,h,6,stone,x,h/2-2,z);for(const dx of [-2,2])for(const dz of [-2,2]){cylinder(.8,h+3,stone,x+dx,(h+3)/2-2,z+dz);mesh(new THREE.ConeGeometry(1.1,3,8),dark,x+dx,h+2,z+dz);}}
for(const x of [-23,23])box(3,24,.15,water,x,-1,-25);
for(let i=0;i<32;i++){const a=i*2.399,r=25+(i%4)*4,x=Math.cos(a)*r,z=Math.sin(a)*r;cylinder(.35,3,wood,x,1,z);mesh(new THREE.ConeGeometry(2.2,6,7),grass,x,5,z);}
// Floor stones and glowing braziers.
for(let i=0;i<60;i++){const x=Math.sin(i*2.3)*13,z=Math.cos(i*1.7)*14;box(1.3,.07,1.1,stone,x,.03,z);}
for(const x of [-11,11])for(const z of [-8,9]){cylinder(.5,1.2,dark,x,.6,z);mesh(new THREE.SphereGeometry(.5,8,8),glow,x,1.5,z);}
function humanoid(color,index){const g=new THREE.Group(),armor=mat(color,.35,.45);box(.85,.95,.5,armor,0,1.4,0,g);box(.55,.4,.4,dark,0,.8,0,g);mesh(new THREE.SphereGeometry(.3,12,8),skin,0,2.13,0,g);mesh(new THREE.ConeGeometry(.38,.6,5),index===0?gold:dark,0,2.5,0,g);const legs=[],arms=[];
 for(const sign of [-1,1]){const leg=new THREE.Group();leg.position.set(sign*.22,.8,0);g.add(leg);box(.25,.8,.28,dark,0,-.4,0,leg);box(.3,.2,.5,dark,0,-.78,.08,leg);legs.push(leg);const arm=new THREE.Group();arm.position.set(sign*.57,1.8,0);g.add(arm);box(.23,.8,.23,armor,0,-.35,0,arm);arms.push(arm);}
 if(index===0){box(.2,1.8,.1,mat(0xc5d8df,.8,.2),0,-1,.35,arms[1]);box(.5,.1,.2,gold,0,-.35,.35,arms[1]);}
 else if(index===1){cylinder(.06,2,gold,0,-.5,.3,arms[1]);mesh(new THREE.SphereGeometry(.2,10,8),new THREE.MeshBasicMaterial({color:0x74d8ff}),0,.5,.3,arms[1]);}
 else {box(.7,.8,.12,gold,0,-.4,.3,arms[0]);box(.35,.6,.4,dark,0,-.7,.4,arms[1]);}
 scene.add(g);return {g,legs,arms};}
const heroes=HEROES.map((h,i)=>humanoid(h.color,i));
const giant=new THREE.Group(),iron=mat(0x3e474e,.6,.65);box(2.5,2.6,1.7,iron,0,3.8,0,giant);box(1.8,.8,1.3,iron,0,2,0,giant);mesh(new THREE.DodecahedronGeometry(.85),iron,0,5.8,0,giant);mesh(new THREE.SphereGeometry(.35,10,8),glow,0,3.9,1,giant);for(const x of [-.32,.32])box(.25,.12,.1,glow,x,5.9,.75,giant);
const giantArms=[];for(const sign of [-1,1]){const a=new THREE.Group();a.position.set(sign*1.6,4.9,0);giant.add(a);mesh(new THREE.DodecahedronGeometry(.85),iron,0,0,0,a);box(.7,2.2,.8,iron,0,-1.2,0,a);mesh(new THREE.DodecahedronGeometry(.65),iron,0,-2.5,0,a);giantArms.push(a);box(.8,1.8,.8,iron,sign*.7,1,0,giant);box(1.1,.5,1.5,iron,sign*.7,.25,.2,giant);}scene.add(giant);
const danger=mesh(new THREE.RingGeometry(3.9,4.2,64),new THREE.MeshBasicMaterial({color:0xff3b45,transparent:true,opacity:.75,side:THREE.DoubleSide}),0,.08,0);danger.rotation.x=-Math.PI/2;
const marker=mesh(new THREE.RingGeometry(.65,.8,32),new THREE.MeshBasicMaterial({color:0x37d8ff,side:THREE.DoubleSide}),0,.06,0);marker.rotation.x=-Math.PI/2;
const effectMeshes=[];for(let i=0;i<8;i++){const e=mesh(new THREE.SphereGeometry(1,12,8),new THREE.MeshBasicMaterial({color:0xffc575,wireframe:true}),0,0,0);e.visible=false;effectMeshes.push(e);}
let game=createGame(),last=performance.now();const keys=new Set();
function start(){game.phase='playing';$('overlay').hidden=true;keys.clear();}
function show(title,text,label,callback){$('overlay').hidden=false;$('overlay').querySelector('article').innerHTML=`<h2>${title}</h2><p>${text}</p><button id="start">${label}</button>`;$('start').onclick=callback;}
function restart(){game=createGame();show('Ruins of Ember','A fresh party and guardian await.','Start encounter',start);keys.clear();}
function pause(){if(!['playing','paused'].includes(game.phase))return;if(game.phase==='playing'){game.phase='paused';show('Encounter paused','Resume when ready.','Resume',start);}else start();keys.clear();}
$('start').onclick=start;$('pause').onclick=pause;$('restart').onclick=restart;$('attack').onclick=()=>attack(game);$('ability').onclick=()=>attack(game,true);$('heal').onclick=()=>heal(game);$('dodge').onclick=()=>dodge(game);
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase());if(e.repeat)return;const k=e.key.toLowerCase();if(k==='j')attack(game);if(k==='k')attack(game,true);if(k==='h')heal(game);if(k===' ')dodge(game);if(k==='escape')pause();if(['1','2','3'].includes(k))switchHero(game,Number(k)-1);});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{keys.clear();if(game.phase==='playing')pause();});
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key.toLowerCase());});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(b.dataset.key.toLowerCase()));}
// Create party buttons once so pointer and keyboard focus remain stable.
$('party').innerHTML=HEROES.map((h,i)=>`<button data-hero="${i}"><b>${h.name}</b><span id="hp-${i}"></span><progress id="bar-${i}" max="${h.hp}" value="${h.hp}"></progress><small id="mp-${i}"></small></button>`).join('');for(const b of document.querySelectorAll('[data-hero]'))b.onclick=()=>switchHero(game,Number(b.dataset.hero));
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();
const map=$('map').getContext('2d');function minimap(){map.clearRect(0,0,170,170);map.strokeStyle='#8dbfa4';map.strokeRect(12,12,146,146);[...game.party,game.boss].forEach((p,i)=>{map.fillStyle=i===3?'#ff694f':i===game.selected?'#28dcff':'#c6cb8b';map.beginPath();map.arc(85+p.x*3.7,85+p.z*3.7,i===3?6:4,0,Math.PI*2);map.fill();});}
function frame(now){const dt=Math.max(0,(now-last)/1000);last=now;const previous=game.phase;tick(game,{x:(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),z:(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0),block:keys.has('l')},dt);
 game.party.forEach((p,i)=>{const m=heroes[i];m.g.position.set(p.x,p.dodge>0?.35:0,p.z);m.g.rotation.y=p.swing>0?Math.atan2(game.boss.x-p.x,game.boss.z-p.z):p.heading;m.g.visible=p.hp>0;const walk=game.phase==='playing'&&((i===game.selected&&keys.size>0)||i!==game.selected)?Math.sin(game.time*9)*.25:0;m.legs[0].rotation.x=walk;m.legs[1].rotation.x=-walk;m.arms[1].rotation.x=p.swing>0?-1.7+Math.sin(p.swing*15):p.blocking?-1:0;$(`hp-${i}`).textContent=`${Math.ceil(p.hp)} / ${p.maxHp} HP`;$(`bar-${i}`).value=p.hp;$(`mp-${i}`).textContent=`MP ${Math.floor(p.mp)} / 100`;$('party').children[i].classList.toggle('selected',i===game.selected);});
 giant.position.set(game.boss.x,0,game.boss.z);giant.rotation.y=Math.atan2(active(game).x-game.boss.x,active(game).z-game.boss.z);for(const a of giantArms)a.rotation.x=game.boss.state==='telegraph'?-1.8:game.boss.state==='recover'?.5:Math.sin(game.time*2)*.12;iron.emissive.setHex(game.boss.flash>0?0x883b12:0x000000);giant.visible=game.boss.hp>0;
 danger.visible=game.boss.state==='telegraph';if(game.boss.target){danger.position.x=game.boss.target.x;danger.position.z=game.boss.target.z;danger.scale.setScalar(1+Math.sin(game.time*15)*.025);}
 const p=active(game);marker.position.set(p.x,.06,p.z);const desired=new THREE.Vector3(p.x*.65+9,10,p.z+16);camera.position.lerp(desired,Math.min(1,dt*6));camera.lookAt(p.x*.5,2,p.z-4);
 effectMeshes.forEach((m,i)=>{const e=game.effects[i];m.visible=!!e;if(e){m.position.set(e.x,1.5,e.z);m.scale.setScalar(1+(1-e.life)*3);m.material.color.setHex(e.color);}});
 $('boss-hp').value=game.boss.hp;$('boss-state').textContent=game.boss.state.toUpperCase();$('message').textContent=game.message;$('heal').firstChild.textContent=`Healing potion (${game.potions}) `;$('ability').disabled=game.phase!=='playing'||p.mp<30||p.abilityCooldown>0;$('attack').disabled=game.phase!=='playing'||p.cooldown>0;$('dodge').disabled=game.phase!=='playing'||p.mp<15||p.dodge>0;$('heal').disabled=game.phase!=='playing'||game.potions===0||p.hp===p.maxHp;minimap();
 if(previous==='playing'&&['won','lost'].includes(game.phase))show(game.phase==='won'?'Guardian defeated':'Party defeated',`Encounter time ${game.time.toFixed(1)} seconds`,'Play again',restart);
 renderer.render(scene,camera);requestAnimationFrame(frame);}
requestAnimationFrame(frame);window.fightingDiagnostics=()=>({phase:game.phase,time:game.time,selected:game.selected,x:active(game).x,z:active(game).z,hp:active(game).hp,mp:active(game).mp,bossHp:game.boss.hp,potions:game.potions,bossState:game.boss.state,hits:game.hits,webgl:!!renderer.getContext()});
